### ISSUE TITLE
Mouse pointer misaligns with Start and Exit buttons on first screen.

### ISSUE THREAD

**Issue by kfogel** [Snipie/Conway-s-game-of-life-clone#1]
On the first screen, the area of mouse sensitivity for the Start and Exit buttons is displaced from the displayed boundaries of those buttons.  See attached video for a demonstration.

This is on a Debian GNU/Linux system ("testing" distro, up-to-date as of this morning) and GNOME Shell 3.22.3.  I compiled with `gcc main.c -o game -lGL -lglut -lGLU`, using GCC 6.3.0 20170415 ("Debian 6.3.0-14"), GL 1.1.1, GLU 1.1.1, and glut... well, I can't tell from `/usr/include/GL/freeglut_std.h` exactly what freeglut version I have, but this might help:

    #define  FREEGLUT             1
    #define  GLUT_API_VERSION     4
    #define  GLUT_XLIB_IMPLEMENTATION 13

[Snipie-github-conway-life-75be43f-button-misalignment.zip](https://github.com/Snipie/Conway-s-game-of-life-clone/files/970810/Snipie-github-conway-life-75be43f-button-misalignment.zip)

**Comment by Snipie** [comment]
Thank you for your time making this carefully crafted issue, to say the least.
Your issue should be fixed by 8b704f6

**Comment by kfogel** [comment]
Confirmed that this fixes the bug for me.  Thanks!

By the way, it's a common practice to put the issue number in the commit message, for example: "Fix mouse pointer misalignment (#1)".  As long as there is a "#" sign, the commit and the issue will be automatically linked to each other, in GitHub and in other tools that know about this convention.

**Comment by Snipie** [comment]
Closed
